services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      DB_PATH: "/app/data/myapp.sqlite"
      NODE_ENV: development
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
