@echo off

echo Starting Docker Compose and rebuilding containers...
docker-compose up --build -d

echo Running migrations...
docker-compose exec app npx sequelize-cli db:migrate

echo Running unit tests...
docker-compose exec app npm test

echo Cleaning up and removing containers...
docker-compose down
